import * as React from "react";
import "../styles/FakeJson.scss"



export class FakeJson extends React.Component <{}, {images: any[], image_titles: any[], album_num: string}>{    
    constructor(props:any) {
        super(props);
        this.state = {
            images: [],
            image_titles: [],
            album_num: "",
        }
        this.handleChange = this.handleChange.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);
    }

    handleChange(event){
        this.setState({album_num: event.target.value});
    }

    handleSubmit(event){
        event.preventDefault();
        
        let target_int = parseInt(this.state.album_num);
        if (isNaN(target_int)){
            return;
        }
        if (target_int >= 1 && target_int <= 100){
            //console.log(event.target.value);
            
            let fetch_url = 'https://jsonplaceholder.typicode.com/photos?albumId=';
            fetch_url += this.state.album_num;
            


            fetch(fetch_url)
            .then(response => response.json())
            .then(data => {
                let images = data.map( (value)=>{
                    return (
                        <img src={value.thumbnailUrl} alt={value.title}/>
                    );
                } );
                let image_titles = data.map( (value)=>{
                    return (<p>{value.title}</p>);
                });
                this.setState({
                    images: images,
                    image_titles: image_titles,
                });
            })
        }
        return;


    }
    
    /*

    componentDidMount(){
        fetch('https://jsonplaceholder.typicode.com/photos?albumId=1')
        .then(response => response.json())
        .then(data => {
            let images = data.map( (value)=>{
                return (
                    <img src={value.thumbnailUrl} alt={value.title}/>
                );
            } );
            let image_titles = data.map( (value)=>{
                return (<p>{value.title}</p>);
            });
            this.setState({
                images: images,
                image_titles: image_titles,
            });
        })
    }*/
    


    render() {
        let fake_json;
        fake_json = this.state.images.map((value, index)=>{
            return (<div>{value}{this.state.image_titles[index]}</div>);
        });



        return (<div>
                <p id="fake_json_intro">
                    The following images and titles are generated by fetching online JSON API.
                </p>

                <form onSubmit={this.handleSubmit} id="fake_json_form">
                  <label>
                    Which album do you want to see (Valid number: 1-100):<br/>
                    <input type="text" value={this.state.album_num} onChange={this.handleChange}/>
                
                  </label>
                  <br/>
                  <input type="submit" value="Update"/>
                </form>

                <div id="fake_json">
                    {fake_json}
                </div>
                </div>);
    }
}